image: node:18

stages:
  - build
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEV_SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $DEV_HOST > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install --progress=false
    - NODE_ENV=production GENERATE_SOURCEMAP=false npm run build
    - scp -r -B dist/* $DEV_USER@$DEV_HOST:/var/www/interns/contract/
  only:
    - master
